#set page(
  paper: "a4",
  margin: (x: 2.2cm, y: 2.4cm),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(size: 8pt, fill: gray)
      _6-node hybrid SDP-SOCP T&D case study_
      #h(1fr) TSO-DSO project
      #linebreak()
    ]
  },
  numbering: "1",
)
#set text(font: "New Computer Modern", lang: "en", size: 10.5pt)
#set par(justify: true, leading: 0.65em)
#set heading(numbering: "1.1")
#show heading.where(level: 1): it => v(0.8em) + it
#show heading.where(level: 2): it => v(0.4em) + it
#show table: set text(size: 9pt)

// Figures live in results/td_hybrid_6node/ (regenerated by the script, not tracked) and lie
// outside this file's directory. A plain `typst compile docs/writeups/td_hybrid_6node_case_study.typ`
// therefore shows a file reference in place of each figure; to embed them run (repo root):
//   typst compile --root . --input figures=on docs/writeups/td_hybrid_6node_case_study.typ
#let show-figures = sys.inputs.at("figures", default: "off") == "on"
#let resfig(name, width: 90%) = if show-figures {
  image("/results/td_hybrid_6node/" + name + ".png", width: width)
} else {
  block(
    width: width,
    inset: 8pt,
    stroke: 0.5pt + gray,
  )[#text(fill: gray)[Figure file `results/td_hybrid_6node/#name.pdf` (compile with `--root . --input figures=on` to embed).]]
}

#align(center)[
  #text(size: 19pt, weight: "bold")[The 6-node hybrid SDP-SOCP T&D case study]
  #v(0.3em)
  #text(size: 12pt, fill: gray)[Independent reproduction, global-optimality check, ADMM stress tests, congestion and inexactness]
  #v(0.8em)
  #line(length: 60%, stroke: 0.5pt + gray)
  #v(0.8em)
]

_Companion script: `scripts/td_hybrid_6node_case_study.jl`. Every number in this document is copied from the committed outputs of its final run, `results/td_hybrid_6node/summary.txt` and the CSV files next to it. The figures are regenerated by the script (PDF and PNG in `results/td_hybrid_6node/`, not tracked); run the script before compiling this document._

= Purpose and the paper being backed

This document backs the draft paper by J. P. Palacios et al., _"Convexification Strategies for Optimal Power Flow in Coupled Transmission and Distribution Networks"_ (draft of 2026-09-29), Sections VII and VIII. The paper builds a hybrid convex relaxation of a 6-node transmission-and-distribution (T&D) system. The meshed transmission nodes 1-3 are a $3 times 3$ Hermitian positive semidefinite block $W$ (SDP). The radial feeder 3-4-5-6 is the DistFlow model with its second-order-cone (SOC) relaxation. The two parts are coupled at the boundary bus 3 through $W_(33) = v_3$. The paper then decomposes the problem between the TSO and the DSO with a Gauss-Seidel ADMM.

The case study has five parts:

+ *Experiment 0, baseline self-check.* Reproduce the paper's monolithic optimum and stop with an error if any published number is missed.
+ *Experiment 1, global optimality.* Solve the non-convex AC-OPF with Ipopt from many starts. This tests the claim that the relaxed solution is the global AC optimum.
+ *Experiment 2, ADMM.* Re-run the paper's ADMM and stress its two guidance statements: "$rho$ on the scale of the prices" and "$epsilon$ small or zero".
+ *Experiment 3, congestion.* The paper leaves this for future work.
+ *Experiment 4, inexact regimes.* Also left for future work by the paper. Includes the effect and cost of the LinDistFlow exactness copy.

Disagreements with the paper are reported as found. The experiments were not tuned to make the paper look right.

= System, model and implementation

== Data and conventions

The data are those of the paper's Table I. $S_"base" = 100$ MVA. Transmission lines (1,2), (2,3), (1,3) use the $pi$ model with total charging $b$ and $S^max = 2.0$ pu. Feeder branches (3,4), (4,5), (5,6) have $S^max = I^max = 1.0, 0.6, 0.4$ pu. Loads are $P_d = (0, 0.90, 0.60, 0.12, 0.10, 0.08)$ and $Q_d = (0, 0.30, 0.20, 0.05, 0.04, 0.03)$ pu. Generation cost is $1100 P_g^2 + 2000 P_g + 100$ \$/h with $0 <= P_g <= 3$ and $-1.5 <= Q_g <= 1.5$. All $|V| in [0.95, 1.05]$. Prices are balance duals in \$/h per pu divided by 100, i.e. \$/MWh (\$/Mvarh). Nodes 1-3 are priced from the SDP balances, nodes 4-6 from the DistFlow balances.

== What is reused from the framework and what is new

The model builders never name a solver. Clarabel (SOCP/SDP) and Ipopt (NLP) come from the framework's solver factory `select_optimizer`. The following are framework pieces:

- the validated radial `Feeder` for nodes 3-6;
- the "framework-hosted" DSO block built by `contribute!(ConvexBranchFlow(), ...)` on the same JuMP model as the SDP block, with `add_to_residual!` and `close_balance!` for the balances;
- the exactness gate `assert_socp_exact!` and its hybrid floor $max(tau, epsilon dot S_max^2)$ with $tau = 2 times 10^(-7)$, $epsilon = 10^(-9)$ and $"rtol" = 10^(-4)$;
- the feeder DLMP decomposition `decompose_dlmp`;
- the Baran-Wu phasor recovery `recover_voltage_angles`.

Four pieces are new and live in the script:

- the transmission SDP block (paper eqs. 20-28);
- a paper-faithful DistFlow block (eqs. 29-33) with an optional mirror of the framework's exactness copy;
- the TSO and DSO ADMM subproblems (eqs. 35-42). They are built once; each iteration only resets the objective;
- the polar AC-OPF of the full 6-node system.

*Framework finding.* `ConvexBranchFlow` fixes the feeder-root squared voltage $v$ and its copy $hat(v)$ at 1.0. It therefore cannot represent a T&D boundary where $v_3 = W_(33)$ is a decision variable. The script works around this without changing the framework:

+ after `contribute!`, unfix the root $v$ and $hat(v)$;
+ re-impose the squared-voltage bounds on the root;
+ add $v_"root" = "Re"(W_(33))$ and $hat(v)_"root" = v_"root"$;
+ inject the boundary import, which is shared with the SDP node-3 balance, into the residuals.

The framework block differs from the paper model in three ways:

- it adds a receiving-end apparent-power cone on every limited branch, where the paper has only the sending end;
- it always carries the exactness copy;
- it has no current limit $l <= I_max^2$, so the script adds one.

At the baseline the two models agree to $9.85 times 10^(-7)$ \$/h in cost and $2.4 times 10^(-5)$ \$/MWh in prices. `assert_socp_exact!` passes (max $|l v - P^2 - Q^2| = 7.0 times 10^(-11)$), and the framework's phasor recovery matches the script's recursion to $5.9 times 10^(-11)$ pu.

*Solver setting (measured).* With Clarabel's default equilibration, the monolithic solve stops at the same iterate for every tolerance from $10^(-7)$ to $10^(-9)$. The status is OPTIMAL at $10^(-7)$ and ALMOST_OPTIMAL below. The cone residual on (3,4) is $1.1 times 10^(-7)$, and the balance duals deviate from finite differences by up to $7 times 10^(-4)$ \$/MWh. Disabling equilibration reaches OPTIMAL at $10^(-9)$, and the duals then agree with finite differences. The script therefore uses this setting throughout. There is one exception: if a solve ends in a numerical failure, it is repeated once with equilibration on, and the result records which setting was used.

= Experiment 0: baseline reproduction

The baseline gate compares about 40 quantities with the paper's printed values. Each tolerance is the paper's printed half-unit, which sits just above the measured deviation. The gate *passed*. @tab-baseline lists the main quantities.

#figure(
  table(
    columns: (1.1fr, 1.3fr, 1.3fr, 0.9fr),
    align: (left, right, right, right),
    [*Quantity*], [*This script*], [*Paper*], [*|dev|*],
    [Cost (\$/h)], [7461.1052], [7461.105], [1.81e-04],
    [$P_g$ / $Q_g$ (pu)], [1.8328719 / 0.1338106], [1.83287 / 0.13381], [1.9e-06 / 6.0e-07],
    [$P_(34)$ / $Q_(34)$ (pu)], [0.30486269 / 0.12926442], [0.30486 / 0.12926], [2.7e-06 / 4.4e-06],
    [$|V_3|$ (pu)], [1.0140527], [1.01405], [2.68e-06],
    [Losses total / transm. / feeder (pu)], [0.032872 / 0.028009 / 0.004863], [0.0329 / 0.0280 / 0.0049], [$<= 3.7 times 10^(-5)$],
    [$lambda_1(W)$], [3.1736626], [3.1737], [3.74e-05],
    [$|lambda_2 / lambda_1|$], [1.01e-11], [$< 10^(-9)$], [--],
    [$V_1, V_2, V_3$], [1.05000∠0°, 1.02121∠−4.948°, 1.01405∠−5.966°], [1.0500∠0°, 1.0212∠−4.95°, 1.0141∠−5.97°], [$<= 4.7 times 10^(-5)$ pu, $4 times 10^(-3)$°],
    [Cone residuals (3,4), (4,5), (5,6)], [4.67e-10, 2.15e-11, 9.84e-11], [2.6e-7, 2.9e-8, 2.3e-8], [--],
    [Loading line (1,2) / feeder], [56.90 % / 33.11, 32.95, 21.57 %], [56.9 % / 33.1, 33.0, 21.6 %], [$<= 4.8 times 10^(-4)$],
  ),
  caption: [Monolithic hybrid optimum: this script vs the paper (Sec. VIII-B, Table II).],
) <tab-baseline>

The paper's cone residuals are a factor of 100-1000 larger than ours. Both are "zero within solver tolerance": the size of the residual depends on the solver's accuracy, not on the model.

#figure(
  table(
    columns: 7,
    align: (center, right, right, right, right, right, right),
    [*Node*], [*$pi_P$ dual*], [*$pi_P$ FD*], [*Paper*], [*$pi_Q$ dual*], [*$pi_Q$ FD*], [*Paper*],
    [1], [60.32318], [60.32318], [60.323], [−0.00000], [−0.00000], [0.000],
    [2], [61.88077], [61.88077], [61.881], [0.41096], [0.41095], [0.411],
    [3], [62.59037], [62.59037], [62.590], [0.53662], [0.53659], [0.537],
    [4], [62.99455], [62.99456], [62.995], [0.73607], [0.73605], [0.736],
    [5], [64.93110], [64.93108], [64.931], [1.50653], [1.50650], [1.507],
    [6], [65.94119], [65.94116], [65.941], [1.88880], [1.88877], [1.889],
  ),
  caption: [Monolithic nodal prices (\$/MWh, \$/Mvarh): balance duals, central finite differences of the optimal cost ($h = 10^(-4)$ pu) and the paper's Table III. The largest dual-FD mismatch is $3.2 times 10^(-5)$.],
) <tab-prices>

All 12 prices round to the paper's Table III values (@tab-prices); the largest deviation is $4.7 times 10^(-4)$ \$/MWh. An earlier reproduction disagreed with the Table III "mono" column in the third decimal (62.994 vs 62.995, 1.506 vs 1.507, 1.888 vs 1.889). That reproduction used Clarabel's default equilibration, which ended ALMOST_OPTIMAL. With the accurate solve, finite differences and duals agree to $3 times 10^(-5)$ and match the paper, so *those third-decimal differences were solver accuracy, not an error in the paper*.

Two further checks hold:

- at node 1, $(2 c_2 P_g + c_1)/100 = 60.32318 = pi_(P,1)$;
- the price spread is 3.3508 \$/MWh across the feeder and 2.2672 \$/MWh across the transmission network (paper: 3.35 and 2.27).

= Experiment 1: global optimality

Ipopt ($"tol" = 10^(-10)$) solved the polar AC-OPF of the full 6-node system from 26 starts:

- a flat start;
- 20 seeded random starts with $|V| tilde U[0.95, 1.05]$, $theta tilde U[-0.3, 0.3]$ rad and $P_g, Q_g$ uniform within their bounds;
- the framework's 5 deterministic Ipopt strategy variants.

The AC model uses the relaxation's limits:

- transmission $|S|$ limits at both line ends;
- feeder sending-end $|S|$ limits;
- the current limit $|S_(i j)|^2 / |V_i|^2 <= I_max^2$.

*All 26 starts were locally solved and reached a single optimum*, 7461.105178 \$/h. The relaxation's cost is 7461.105181 \$/h, so the gap (AC − relaxation)/AC is $-3.98 times 10^(-10)$. The relaxation is above the AC value by $3 times 10^(-6)$ \$/h. This is below Clarabel's $10^(-9)$ relative accuracy, so the gap is zero within solver tolerance.

The relaxed point is also AC feasible:

- the voltages recovered from $W$'s leading eigenvector, extended down the feeder by the Baran-Wu recursion, differ from the Ipopt optimum by at most $1.25 times 10^(-8)$ pu (complex);
- substituted into the full 6-node admittance matrix, they leave AC injection mismatches of $1.28 times 10^(-10)$ pu (P) and $7.87 times 10^(-10)$ pu (Q);
- the recovered voltages are $V_4 = 1.00354∠−6.923°$, $V_5 = 0.98454∠−7.225°$ and $V_6 = 0.97500∠−7.398°$.

This confirms with an independent non-convex solver the paper's claim that the relaxed solution is the global AC-OPF optimum on this case.

= Experiment 2: TSO-DSO ADMM

The paper's Gauss-Seidel ADMM was re-implemented as specified (eqs. 35-42):

- $rho = 500$, $epsilon = 10^(-2)$;
- $lambda^((0)) = 0$ and $y_D^((0)) = (1, sum P_d, sum Q_d)$;
- stop when the primal residual $||y_T - y_D||_2 < 10^(-4)$ pu and the dual residual $rho ||Delta y_D||_2 < 10^(-2)$.

All subproblem solves ended OPTIMAL.

#figure(
  table(
    columns: 5,
    align: (left, right, right, right, right),
    [*Quantity*], [*Mono (here)*], [*ADMM (here)*], [*Mono (paper)*], [*ADMM (paper)*],
    [Cost (\$/h)], [7461.105], [7460.537], [7461.105], [7460.537],
    [$P_g$ (pu)], [1.83287], [1.83278], [1.83287], [1.83278],
    [$Q_g$ (pu)], [0.13381], [0.13379], [0.13381], [0.13379],
    [$P_(34)$ TSO side (pu)], [0.30486], [0.30477], [0.30486], [0.30477],
    [$Q_(34)$ TSO side (pu)], [0.12926], [0.12926], [0.12926], [0.12926],
    [$|V_3|$ (pu)], [1.01405], [1.01406], [1.01405], [1.01406],
    [$|lambda_2/lambda_1|$ of $W$], [1.01e-11], [7.53e-14], [6.4e-10], [5.9e-11],
    [Max. cone residual], [4.67e-10], [8.66e-10], [2.6e-7], [2.4e-9],
    [Iterations], [--], [57], [--], [57],
    [Final primal / dual residual], [--], [9.08e-05 / 1.02e-03], [--], [9.1e-5 / 1.8e-3],
  ),
  caption: [Table II side by side. Relative cost difference (mono − ADMM)/mono: $7.61 times 10^(-5)$ here, $7.6 times 10^(-5)$ in the paper.],
) <tab-admm>

The reproduction matches the paper almost exactly (@tab-admm):

- 57 iterations;
- final primal residual $9.08 times 10^(-5)$ pu;
- ADMM cost 7460.537 \$/h;
- all Table II quantities to the printed digits.

The only difference is the final dual residual, $1.02 times 10^(-3)$ here versus $1.8 times 10^(-3)$ in the paper. Both are below the $10^(-2)$ threshold. The other numbers match to the printed digits, so the paper's dual residual may use a slightly different definition or norm.

The other claims also hold:

- all six active prices are within 0.1 % of the monolithic ones from *iteration 39* on (paper: "about 40");
- at convergence they are within 0.0039 % (paper: 0.004 %), and the reactive prices are within $1.6 times 10^(-4)$ \$/Mvarh;
- the boundary multiplier satisfies $-lambda_p = 6258.8038$ \$/h per pu $= pi_(P,3)^"ADMM" dot 100$ (paper: 6258.80);
- likewise $-lambda_q = 53.6549$ vs $pi_(Q,3)^"ADMM" dot 100 = 53.6548$.

#figure(resfig("admm_convergence", width: 95%), caption: [ADMM at $rho = 500$, $epsilon = 10^(-2)$: residuals (left; dashed $10^(-4)$, dotted $10^(-2)$) and total generation cost vs the monolithic optimum (right).])

#figure(resfig("admm_price_evolution", width: 75%), caption: [Active nodal prices during ADMM: solid TSO (nodes 1-3), dashed DSO (nodes 4-6), dotted monolithic values.])

== Penalty parameter sweep

#figure(
  table(
    columns: 7,
    align: right,
    [*$rho$*], [*Iterations*], [*Converged*], [*Primal*], [*Dual*], [*Rel. cost error*], [*Max $|Delta pi_P|$*],
    [50], [523], [yes], [9.79e-05], [5.15e-05], [−8.21e-05], [2.81e-03],
    [100], [264], [yes], [9.80e-05], [2.58e-05], [−8.22e-05], [2.70e-03],
    [200], [135], [yes], [9.33e-05], [9.13e-05], [−7.83e-05], [2.81e-03],
    [500], [57], [yes], [9.08e-05], [1.02e-03], [−7.61e-05], [2.54e-03],
    [1000], [31], [yes], [8.42e-05], [2.03e-03], [−7.06e-05], [2.35e-03],
    [2000], [18], [yes], [7.09e-05], [6.47e-03], [−5.95e-05], [1.93e-03],
    [5000], [11], [yes], [1.52e-05], [7.77e-03], [−1.27e-05], [4.56e-04],
    [10000], [8], [yes], [6.33e-06], [1.49e-05], [−5.28e-06], [2.12e-04],
    [20000], [9], [yes], [5.32e-07], [3.71e-03], [−7.82e-08], [2.50e-05],
  ),
  caption: [$rho$ sweep at $epsilon = 10^(-2)$ (`admm_rho_sweep.csv`).],
) <tab-rho>

The paper's guidance that "$rho$ should be chosen on the scale of these prices" *holds* (@tab-rho):

- iterations fall roughly as $1/rho$, from 523 at $rho = 50$ to a minimum of 8 at $rho = 10000$;
- the fastest settings, $rho in {5000, 10000, 20000}$ with 11, 8 and 9 iterations, bracket $pi_(P,3) dot 100 = 6259$ \$/h per pu;
- every $rho$ converged.

The paper's own choice, $rho = 500$, is about an order of magnitude below the fastest setting and takes 5-7 times more iterations. Larger $rho$ also gives a smaller final cost and price error at the same stopping tolerance.

#figure(resfig("admm_rho_sweep", width: 60%), caption: [ADMM iterations vs $rho$ (log-log); the dashed line marks $pi_(P,3) dot 100$.])

== Loss-penalty sweep

For $epsilon in {0, 10^(-4), 10^(-3), 10^(-2), 10^(-1)}$ at $rho = 500$:

- every run converged in *57 iterations* with the same final cost bias ($-7.61 times 10^(-5)$);
- the largest cone residual over *all intermediate DSO iterates* was between $1.55 times 10^(-9)$ and $2.66 times 10^(-9)$; the largest hybrid-floor ratio over the iterates was $2.46 times 10^(-3)$, far below 1;
- at $epsilon = 0$ the maximum over all iterates was $1.82 times 10^(-9)$, and $5.98 times 10^(-10)$ at convergence.

The paper's statement that "$epsilon$ can be kept small (or set to zero)" therefore *holds on this case*. The DSO subproblem never used the slack in its cones, even in intermediate iterates. The reason is the one the paper gives: the boundary multiplier carries the TSO's positive marginal cost into the DSO objective.

The incentive depends on that price being positive. Experiment 4 shows that when the system is in surplus, the generator sits at $P_g = 0$ and the monolithic relaxation itself loses exactness. The $epsilon = 0$ result should therefore be stated as conditional on a positive boundary price.

#figure(resfig("admm_eps_sweep", width: 60%), caption: [Cone residual vs $epsilon$: maximum over all DSO iterates and at convergence; the dashed line is the framework's solver floor $tau = 2 times 10^(-7)$.])

= Experiment 3: congestion

== The paper's system cannot be congested meaningfully

The planned test was to tighten line (1,2) and the feeder head (3,4) to 0.9 times their baseline flows, i.e. $S^max_(12) = 1.02427$ and $S^max_(34) = I^max_(34) = 0.29802$ pu. *Both are infeasible.* The relaxation is infeasible, which certifies AC infeasibility because it is a relaxation, and Ipopt from 21 starts finds no AC point.

The reason is structural: with one generator and inelastic loads nothing can be redispatched. The flows are fixed by the loads, and only the voltage profile can move them slightly. Minimizing each flow subject to all other constraints gives the band in which such a limit can bind at all:

- line (1,2): $max|S_(12)|$ can be reduced to 1.137122 pu in the relaxation but *not at all* in AC (Ipopt minimum 1.138073 = baseline);
- feeder head: the minimum $|S_(34)|$ equals the baseline 0.331135 pu in both models.

Inside these bands two pathologies appear:

- at the line band midpoint ($S^max_(12) = 1.137598$) the relaxation is feasible but *not rank one* ($|lambda_2/lambda_1| = 1.45 times 10^(-4)$), Ipopt finds no AC point, prices jump to 244 \$/MWh at node 2, and ADMM does not converge in 3000 iterations;
- at the feeder-head band ($S^max_(34) = 0.331135$) the limit binds at a degenerate point and its dual is *not unique*: the same optimum is priced at node 4 as 187.17 \$/MWh by the paper model, 96.77 \$/MWh by the framework-hosted model, and close to the uncongested value by ADMM (spread 132 \$/MWh).

== Congestion with out-of-merit flexibility (extension, not in the paper)

To study congestion with a well-posed redispatch, two out-of-merit resources were added. Both are active-power only, and both are idle at the baseline:

- a generator G2 at node 2 with cost $1100 P_(g 2)^2 + 6500 P_(g 2)$ \$/h, $P_(g 2) <= 1$. Its marginal cost of 65 \$/MWh exceeds the baseline $pi_(P,2) = 61.88$;
- a DG at node 6 with cost $7000 P_"dg"$ \$/h, $P_"dg" <= 0.2$. Its 70 \$/MWh exceeds the baseline $pi_(P,6) = 65.94$.

The script checks that this extension leaves the baseline unchanged: $|Delta "cost"| = 6.1 times 10^(-5)$ \$/h, max $|Delta pi| = 1.9 times 10^(-4)$ \$/MWh. A first version also gave G2 a reactive range. Even at $P_(g 2) = 0$ that range lowered the baseline cost by 7.4 \$/h through voltage support, so it was not out of merit and was removed. The planned 0.9× limits then apply as specified.

#figure(
  table(
    columns: 4,
    align: (left, right, right, right),
    [], [*Line (1,2) congested*], [*Head (3,4) congested*], [*Both*],
    [Cost (\$/h), change vs baseline], [7565.7044 (+1.4019 %)], [7477.8852 (+0.2249 %)], [7570.7259 (+1.4692 %)],
    [Redispatch], [$P_(g 2) = 0.15575$], [$P_"dg" = 0.03371$], [$P_(g 2) = 0.13219$, $P_"dg" = 0.03369$],
    [Binding limit, shadow price (\$/MVAh)], [(1,2) receiving end 14.1496], [(3,4) sending end 6.0947], [13.8148 and 2.2997],
    [$pi_P$ nodes 1-6], [56.81, 68.43, 65.62, 66.11, 68.17, 69.25], [59.52, 61.03, 61.68, 67.66, 69.37, 70.00], [56.54, 67.91, 65.12, 67.66, 69.37, 70.00],
    [$|lambda_2/lambda_1|$; max cone ratio], [4.01e-11; 1.26e-04], [5.53e-11; 3.46e-04], [3.24e-12; 1.79e-05],
    [AC gap (Ipopt, 21 starts)], [−7.01e-10], [−1.26e-09], [−1.97e-09],
    [ADMM iterations; rel. cost diff], [45; 6.51e-05], [57; 7.14e-05], [46; 6.52e-05],
    [ADMM max $|Delta pi_P|$; $-lambda_p$ vs $pi_(P,3) dot 100$], [1.21e-03; 6562.356 = 6562.356], [2.19e-03; 6168.054 = 6168.054], [1.15e-03; 6511.934 = 6511.934],
  ),
  caption: [Congestion with the out-of-merit extension (`congestion_summary.csv`, `congestion_prices.csv`).],
) <tab-cong>

With redispatch available (@tab-cong):

- *both relaxations stay exact* under congestion;
- the AC gap is at most $2 times 10^(-9)$;
- ADMM converges in 45-57 iterations to within $1.2 times 10^(-3)$-$2.2 times 10^(-3)$ \$/MWh of the monolithic prices;
- the boundary identity $-lambda_p = pi_(P,3) dot 100$ holds to the printed digits.

The prices behave as expected:

- line congestion splits the transmission prices: node 1 falls to 56.81 \$/MWh and equals $2 c_2 P_g + c_1$; node 2 rises to 68.43 \$/MWh, equal to G2's marginal cost;
- head congestion makes the DG marginal: node 6 is priced at exactly 70.00 \$/MWh.

The feeder DLMPs were decomposed with the framework's `decompose_dlmp` after `assert_socp_exact!`. The components sum to the nodal price within $1.4 times 10^(-14)$, and the totals match the paper-model prices within $7.6 times 10^(-5)$ \$/MWh. The decomposition for the head-congested case is shown below.

#figure(
  table(
    columns: 7,
    align: right,
    [*Node*], [*Energy*], [*Cone (loss)*], [*Congestion*], [*Drop*], [*Total*], [*Reactive*],
    [3], [61.6827], [0.0000], [0.0000], [0.0000], [61.6827], [0.4992],
    [4], [61.6827], [0.4584], [5.5135], [0.0035], [67.6581], [3.3339],
    [5], [61.6827], [2.1663], [5.5135], [0.0069], [69.3694], [4.1613],
    [6], [61.6827], [2.7969], [5.5135], [0.0069], [70.0000], [4.5705],
  ),
  caption: [Feeder DLMP decomposition, head (3,4) congested (`congestion_dlmp.csv`, \$/MWh). The energy component is the node-3 boundary price; in the uncongested baseline the congestion column is zero and the cone (loss) term reaches 3.3381 at node 6.],
)

On the transmission side the SDP balances are written in $W$ (traces $"Tr"(Phi_k W)$), not as radial branch flows, so the radial path-sum decomposition does not apply. The script reports three quantities there:

- the reference price at node 1, which equals $2 c_2 P_g + c_1$ in every variant;
- the shadow price of the binding line;
- the nodal spreads, e.g. $pi_(P,2) - pi_(P,1) = 11.6133$ \$/MWh under line congestion.

#figure(resfig("congestion_prices", width: 95%), caption: [Active and reactive nodal prices: baseline vs line-congested, head-congested and both (extension with out-of-merit G2 and DG).])

= Experiment 4: inexact regimes and the exactness copy

Non-curtailable PV with $Q = 0$ was swept as a negative load from 0 to 3.0 pu in steps of 0.05 pu. Each point was solved three ways:

- without the exactness copy;
- with a script-local mirror of the framework's Gan-Low copy;
- with the framework-hosted model (copy plus receiving-end cone).

The AC ground truth is Ipopt from a flat start and 5 seeded random starts. Where the relaxation without copy is infeasible, the AC problem is certified infeasible. The first point of each sweep where Ipopt failed while the relaxation was feasible was re-solved with 20 random starts and 5 strategy variants. The search grid was fixed in advance:

- *Stage A*: Table I ratings, PV at node 6, loads 100 % and 50 % (the planned sweep);
- *Stage B*: Table I ratings, PV at node 5 (an extension, because A found no inexact regime);
- *Stage C*: feeder ratings lifted to $S^max = I^max = 3$ pu on all three branches, PV at node 6, loads 100 %, 50 % and 25 %. This removes the thermal bottleneck that caps the PV in A and B.

#figure(
  table(
    columns: 6,
    align: (left, right, right, right, left, right),
    [*Sweep*], [*Largest feasible PV: relax. / AC / copy (pu)*], [*Max relax. gap where AC solved*], [*Relaxation inexact at PV*], [*Copy*], [*Copy conservatism max (mean)*],
    [A, node 6, 100 %], [0.45 / 0.45 / 0.45], [3.13e-09], [none], [exact], [8.03e-05 (1.30e-05)],
    [A, node 6, 50 %], [0.45 / 0.45 / 0.45], [2.62e-09], [none], [exact], [1.91e-04 (3.94e-05)],
    [B, node 5, 100 %], [0.80 / 0.80 / 0.80], [2.90e-09], [none], [exact], [2.21e-04 (3.42e-05)],
    [B, node 5, 50 %], [0.70 / 0.70 / 0.70], [2.44e-09], [none], [exact], [5.03e-04 (8.44e-05)],
    [C, node 6, 100 %], [1.40 / 0.80 / 1.15], [2.72e-09], [0.85-1.40 (12 points)], [inexact 0.80-1.15], [2.92e-02 (1.86e-03)],
    [C, node 6, 50 %], [1.65 / 0.70 / 1.10], [4.61e-09], [0.75-1.65 (19 points)], [inexact 0.70-1.10], [2.83e-02 (2.12e-03)],
    [C, node 6, 25 %], [1.45 / 0.45 / 1.10], [7.05e-09], [0.50-1.45 (20 points)], [inexact 0.50-1.10], [1.34e-03 (2.20e-04)],
  ),
  caption: [PV back-feed sweeps (`inexact_pv_sweep.csv`). Copy conservatism is (copy cost − AC optimum)/AC optimum over the points where Ipopt found an AC point.],
) <tab-inexact>

*With the paper's ratings (stages A and B) there is no inexact regime.* At all 52 feasible points the relaxation is exact in both blocks and matches the AC optimum within $3.13 times 10^(-9)$. It becomes infeasible at exactly the PV level where Ipopt stops finding AC points, on the 0.05 pu grid. The PV limits are 0.45 pu at node 6 and 0.80 / 0.70 pu at node 5. Two features of this regime matter. The feeder thermal and voltage limits cap the back-feed long before the generator could reach $P_g = 0$. The voltage upper bound at node 6 does bind (from PV 0.40 pu at 100 % load), yet the relaxation stays exact.

*With lifted feeder ratings (stage C) an inexact regime appears*, always beyond the AC-feasible range. Over 51 points the relaxation is feasible, but Ipopt finds no AC point at any of them, including with the deepened searches. In the AC model the voltage limits make these PV levels infeasible. The relaxation instead reports a feasible, priced operating point with large fictitious losses: cone residuals up to 4.81, 7.33 and 5.70 pu at 100 %, 50 % and 25 % load. Two mechanisms produce it:

- *Loads at 100 % and 50 %.* $|V_6|$ sits at the upper bound and another node at the lower bound. Inflating $l$ on (5,6) adds fictitious reactive absorption $x l$ and lowers $v_6$, which no AC point can do. The SDP block stays rank one ($|lambda_2/lambda_1| <= 6.7 times 10^(-11)$).
- *Loads at 25 %, the surplus case.* $P_g$ reaches its lower bound 0, the cost is the constant 100 \$/h, and the surplus is dissipated in fictitious losses. *Here the SDP block also loses rank one*: $|lambda_2/lambda_1|$ ranges from $4.2 times 10^(-4)$ to $4.6 times 10^(-3)$. This is the only regime in this study where the transmission SDP is inexact.

In every case the paper's a-posteriori tightness test (rank ratio and cone residuals) flags the point, so the test does its job. The practical risk is different: an unverified relaxation would report a *feasible operating point and prices where no AC solution exists*.

*The exactness copy does not cure this regime and is itself conservative.* Where Ipopt found an AC point, the copy costs more than the true AC optimum:

- by at most $8.0 times 10^(-5)$ to $5.0 times 10^(-4)$ relative with the paper's ratings;
- by up to *2.9 %* (2.92e-02 at PV 0.80, 100 % load) and 2.8 % (PV 0.70, 50 % load) with lifted ratings. At those two AC-feasible points the copy model is moreover inexact itself: it is pushed into a slack-cone solution while the relaxation without copy is exact and equal to the AC optimum.

Beyond the AC limit the copy model stays feasible for a range of PV levels and is inexact throughout. It is feasible up to 1.15 pu PV (vs 1.40 without copy) at 100 % load and up to 1.10 pu at 50 % and 25 % load. The copy narrows the falsely feasible range but does not remove it.

The framework-hosted model (copy plus receiving-end cone) agrees with the script's copy model to $<= 3.3 times 10^(-5)$ \$/h in every sweep except B at 50 % load. There it differs by up to 26.2 \$/h because its receiving-end apparent-power limit binds under back-feed, and the paper's model has no such limit.

#figure(resfig("inexact_cone_slack", width: 100%), caption: [Top: largest cone residual vs PV without and with the exactness copy (dashed: framework floor $tau$). Bottom: (relaxation cost − AC optimum)/AC optimum where Ipopt found an AC point. Columns: stage A at 100 % load, stage C at 100 % and 25 % load.])

= Recommendations for the paper text

*Claims the paper can now make, with these numbers:*

+ The monolithic optimum and all of Table III are independently reproduced (JuMP + Clarabel). The cost is 7461.1052 \$/h, and all 12 prices are within $4.7 times 10^(-4)$ \$/MWh of Table III and validated by finite differences to $3.2 times 10^(-5)$. Suggest stating that the prices were checked against finite differences of the optimal cost with $h = 10^(-4)$ pu.
+ Global optimality is confirmed by a non-convex solver. Ipopt from 26 different starts reaches a single AC optimum, 7461.105178 \$/h, equal to the relaxation within $4 times 10^(-10)$. The voltages recovered from $W$ satisfy the full AC equations to $8 times 10^(-10)$ pu.
+ The ADMM results (57 iterations, primal residual $9.1 times 10^(-5)$, cost 7460.537 \$/h, prices settling after about 40 iterations, $-lambda_p = 6258.80$) are reproduced exactly.
+ "$rho$ on the scale of the prices" can be quantified: 523 iterations at $rho = 50$, 57 at $rho = 500$, and 8-11 at $rho in [5000, 20000]$, a range that brackets $pi_(P,3) dot 100 approx 6259$.
+ "$epsilon$ small or zero" can be quantified: with $epsilon = 0$ the cone residual over all intermediate iterates stays $<= 1.8 times 10^(-9)$, and iterations and final bias do not change.

*Statements to soften or reword:*

+ The specific cone residuals (2.6e-7, 2.9e-8, 2.3e-8) depend on the solver's accuracy. The same model gives $4.7 times 10^(-10)$ and below with a more accurate Clarabel setting. Say "below $10^(-6)$, i.e. zero within solver tolerance" and report the solver settings, which matter: Clarabel's default equilibration stops at ALMOST_OPTIMAL with dual errors of order $10^(-3)$ \$/MWh.
+ The final dual residual ($1.8 times 10^(-3)$) did not reproduce ($1.02 times 10^(-3)$ here) although every other ADMM number did. Check its definition or norm in the text.
+ $rho = 500$ is about ten times smaller than the fastest setting. Either use $rho approx pi_(P,3) dot 100$ in the experiment, or state that $rho = 500$ is conservative and give the sweep.
+ The $epsilon = 0$ statement relies on a positive boundary price. Qualify it: in a surplus regime the incentive vanishes, and the coupled relaxation itself becomes inexact (Section 7).

*Future-work sentences that can become results:*

+ Congestion. On the paper's single-generator, inelastic-load system, congestion cannot be studied as such. A 10 % tighter limit on line (1,2) or on the feeder head is infeasible, and the feasible band is degenerate: it is empty in AC for line (1,2). Within it the SDP block loses rank one or the duals are not unique. With minimal out-of-merit flexibility (a generator at node 2, a DG at node 6), both relaxations stay exact under transmission, feeder-head and combined congestion. The AC gap is $<= 2 times 10^(-9)$, ADMM converges in 45-57 iterations, $-lambda_p = pi_(P,3) dot 100$ still holds, and the feeder DLMPs split into energy, loss, congestion and voltage components that sum to the nodal price within $1.4 times 10^(-14)$.
+ Inexactness. With the paper's ratings, PV back-feed at node 5 or 6 never makes the relaxation inexact; its infeasibility coincides with AC infeasibility. With lifted feeder ratings, a regime appears beyond the AC hosting limit in which the relaxation reports a feasible, priced point with fictitious losses (cone residuals up to 7.3 pu). In surplus conditions ($P_g = 0$) the SDP block also loses rank one ($|lambda_2/lambda_1|$ up to $4.6 times 10^(-3)$). The a-posteriori test flags every such point, so the paper's verification step is necessary, not optional. The LinDistFlow exactness copy does not cure this regime: it costs up to 2.9 % more than the AC optimum at AC-feasible points and can itself be inexact there.
