# # IEEE-123 Real Impedances — Public-Data Reduction
#
# This page documents WHERE the modified IEEE-123 fixture's branch impedances actually come
# from ([`ieee123_modified`](@ref), `src/data/ieee123.jl`): a public OpenDSS test-case dataset,
# reduced to positive-sequence R1/X1 per segment via a Fortescue-averaging formula, converted
# Ω → pu ONCE at ingestion. It calls the real [`ieee123_modified`](@ref) end-to-end — never a
# re-implemented reduction — so the numbers below cannot silently drift from the committed data
# (`src/data/ieee123_impedances.jl`, generated by `scripts/reduce_ieee123_impedances.jl`).
#
# ## 1. The public data source
#
# Both files were fetched live, over plain `curl`, no auth, on **2026-07-25**:
#
# - `https://raw.githubusercontent.com/tshort/OpenDSS/master/Distrib/IEEETestCases/123Bus/IEEE123Master.dss`
# - `https://raw.githubusercontent.com/tshort/OpenDSS/master/Distrib/IEEETestCases/123Bus/IEEELineCodes.DSS`
#
# **Casing matters**: `IEEELineCodes.DSS` (exact case) is the only form that resolves —
# `IEEELineCodes.dss` (lowercase extension) 404s on this GitHub mirror. Both vendored files are
# committed under `scripts/data/` so the reduction remains offline-reproducible even if the
# upstream mirror ever changes or disappears (data-provenance/tampering mitigation, not a
# security control in the ASVS sense — see Phase 17 threat register T-17-11).
#
# Only 12 of the 29 `New linecode.*` blocks defined in the shared `IEEELineCodes.DSS` are
# actually referenced by a `LineCode=` in `IEEE123Master.dss` — the rest belong to the
# co-bundled 4/13/34-node IEEE test feeders in the same file. `scripts/reduce_ieee123_impedances.jl`
# first collects the SET of `LineCode=` values genuinely used by `New Line.*` statements, then
# only reduces those 12 blocks.
#
# ## 2. The Fortescue-averaging reduction formula
#
# For an `n×n` symmetric line-code impedance matrix (`n ∈ {1,2,3}`), the positive-sequence
# self/mutual impedance is the classic Fortescue-averaging identity:
#
# ```math
# R_1 = \text{mean}(\text{diag}) - \text{mean}(\text{offdiag}) \qquad (\text{same formula for } X_1)
# ```
#
# For `n = 1` there is no off-diagonal term, so `R1 = rmatrix[1,1]` directly (no reduction
# needed) — this is the short-circuit RESEARCH.md documents for single-phase laterals.
#
# ### Worked example: `linecode.1` (verified against the live file, fetched 2026-07-25)
#
# ```julia
# rmatrix = [0.086666667 0.029545455 0.02907197;
#            0.029545455 0.088371212 0.029924242;
#            0.02907197  0.029924242 0.087405303]
# diag_mean    = (0.086666667 + 0.088371212 + 0.087405303) / 3   # = 0.087481061
# offdiag_mean = (0.029545455 + 0.02907197  + 0.029924242) / 3   # = 0.029513889
# R1 = diag_mean - offdiag_mean   # = 0.057967 Ω/unit-length
#
# xmatrix = [0.204166667 0.095018939 0.072897727;
#            0.095018939 0.198522727 0.080227273;
#            0.072897727 0.080227273 0.201723485]
# diag_mean_x    = (0.204166667 + 0.198522727 + 0.201723485) / 3  # = 0.201470960
# offdiag_mean_x = (0.095018939 + 0.072897727 + 0.080227273) / 3  # = 0.082714646
# X1 = diag_mean_x - offdiag_mean_x   # = 0.118756 Ω/unit-length
# ```
#
# These are exactly the pinned sanity values (`R1 ≈ 0.057967`, `X1 ≈ 0.118756`) that
# `scripts/reduce_ieee123_impedances.jl`'s own `--verify` self-check asserts against, and that
# `src/data/ieee123_impedances.jl`'s `(149, 1)` entry (`LineCode=1`, `Length=0.4`) is built from:
# `R1 × Length = 0.057967 × 0.4 = 0.023186868…`, matching the committed Ω value exactly.
#
# ## 3. The units-trap resolution
#
# Neither `IEEE123Master.dss` nor `IEEELineCodes.DSS` sets `Units=` anywhere in the chain
# (verified by grepping both live files: `Units=` never appears). Per the official OpenDSS
# LineCode documentation, `Units=`, if unspecified, means "it is assumed that the units
# correspond to the length being used in the Line models" — i.e. **no conversion is applied**;
# `Length` and the linecode `rmatrix`/`xmatrix` already share the same implicit unit.
# `[CITED: opendss.epri.com/LineCode1.html]`
#
# `scripts/reduce_ieee123_impedances.jl` therefore computes `z_Ω = R1 × Length` directly, with
# NO scale factor — multiplying by `5280`, `1/5280`, `0.001`, or `1000` here would be the
# classic feet-vs-miles/kft trap and would silently corrupt every impedance by 3-4 orders of
# magnitude. (For citation purposes only, not for the math: the implicit unit is very likely
# "kft" — the same shared file has an inline comment on a different feeder's linecode, `! ohms
# per 1000ft` — but this only affects the wording of the citation, never the arithmetic.)
#
# ## 4. Reduction caveats
#
# - **Transposition assumption**: the Fortescue-averaging reduction assumes (approximately)
#   transposed, balanced 3-phase construction — standard for this class of reduction, not a
#   claim that the physical conductors are perfectly transposed.
# - **Single/two-phase laterals**: handled via the `n = 1` short-circuit in the reduction
#   script's Fortescue routine (`R1 = rmatrix[1,1]` directly, no averaging needed when there is
#   no off-diagonal).
# - **Regulators / capacitors / switches**: absorbed into the fixture's existing near-ideal
#   switch-class impedance (`IEEE123_SWITCH_R`/`IEEE123_SWITCH_X` in `src/data/ieee123.jl`) —
#   NOT actively modeled as real regulator/capacitor devices, per the phase's REQUIREMENTS
#   Out-of-Scope. Only the 117 ordinary (non-switch) branches receive real per-segment Ω data
#   from `IEEE123_BRANCH_RX_OHMS`; the 5 switch/regulator-collapsed edges intentionally keep
#   their pre-existing synthetic near-ideal value (RESEARCH Assumption A2).
#
# ## 5. Live execution: building the real-impedance feeder
#
# [`ieee123_modified`](@ref) is the real ingestion path — topology from `IEEE123_EDGES`
# unchanged, non-switch branch r/x looked up from `IEEE123_BRANCH_RX_OHMS` and converted Ω → pu
# via `to_pu_impedance` at this single ingestion point, switch/regulator edges keeping their
# near-ideal synthetic value.

using TSODSO

feeder = ieee123_modified()

# The radial invariant (`|branches| == |buses| - 1`) is enforced by `Feeder`'s own constructor
# (`assert_radial`, called on every `Feeder(...)` construction) — a violation would already have
# thrown during the call above, not silently passed through. We re-state the check here,
# explicitly, as a citable executed assertion rather than relying on the constructor alone:

length(feeder.branches) == length(feeder.buses) - 1 ||
    throw(ArgumentError("radial invariant violated: |branches| must equal |buses|-1"))

# Bus and branch counts for this fixture:

(length(feeder.buses), length(feeder.branches))

# A spot-check of a real, non-switch branch's converted per-unit impedance — bus terminals
# `(149, 1)` from the worked `linecode.1` example above, after Ω → pu conversion at ingestion:

first(b for b in feeder.branches if b.r > 0 && b.x > 0)
